[ClassVersion("1.0.0.0"), FriendlyName("WaitForFailoverClusterNode")]
class WaitForFailoverClusterNode : OMI_BaseResource
{
    [Key] String ClusterName;
    [Required] String NodeName[];
    [Write] UInt32 RetryIntervalSec;
    [Write] UInt32 RetryCount;
};
