[ClassVersion("1.0.0.0"), FriendlyName("FailoverClusterResourceParameter")]
class FailoverClusterResourceParameter : OMI_BaseResource
{
    [Key] String Id;
    [Required] String ResourceType;
    [Required] String ParameterName;  
    [Required] String ParameterValue;
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;    
};
