[ClassVersion("1.0.0.0"), FriendlyName("FailoverClusterCloudWitness")]
class FailoverClusterCloudWitness : OMI_BaseResource
{
    [Key, ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Required] String AccessKey;
    [Write] String Endpoint;  
    [Required] String AccountName;
    [Write] Boolean Force;
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;    
};
